# Generated by Django 4.1.7 on 2023-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_address_mobile_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
    ]
