# Generated by Django 4.1.7 on 2023-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cartorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kinash',
            field=models.BooleanField(default=False),
        ),
    ]
