# Generated by Django 4.1.7 on 2023-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arecentlyadded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='itop_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
